# pytorch中张量的使用

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!ls
!pwd
%cd drive/My Drive/pytorch/

drive  sample_data
/content
/content/drive/My Drive/pytorch


### 初始化张量

In [4]:
import torch
import numpy as np

In [ ]:
# 直接从数据中获取
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

# 从numpy中获取
np_arry = np.array(data)
x_np = torch.from_numpy(np_arry)
print(x_np)

# 从另外一个张量
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
# 覆盖 x_data 的数据类型
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

In [ ]:
# 使用随机值或常数量
shape = (5,3)
rand_tensor = torch.rand(shape)  # 随机值
ones_tensor = torch.ones(shape)  # 全为1的张量
zeros_tensor = torch.zeros(shape) # 全为0

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

In [15]:
# 张量的属性：张量的属性描述他们的形状，数据类型，和存储他们的设备
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 张量的运算

In [17]:
# 能否使用gpu
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

tensor([[0.1002, 0.4051, 0.4499, 0.8076],
        [0.5469, 0.2691, 0.7400, 0.0573],
        [0.0672, 0.9716, 0.9146, 0.3979]])


In [23]:
# 切片操作 [a:b:c]--->a是首位 b是末尾 c是间隔距离
tensor = torch.ones(4,4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
print('Last :', tensor[:-1:2])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
Last : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [24]:
# 连接张量 torch.cat
tensor1 = torch.ones(2,2)
t1 = torch.cat([tensor1, tensor1, tensor1], dim=1)
print(t1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [43]:
# 算术运算 
# 矩阵相乘 torch.matmul
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
data = [[1, 2],[3, 4]]
# a=np.dot(data,data)
tensor = torch.tensor(data)
print(tensor)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
#y3 = torch.rand_like(tensor)
y4 = torch.matmul(tensor,tensor.T)
#torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y4)

# 矩阵*乘
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
# z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
z3 = torch.mul(tensor, tensor)
print(z1) 
print(z2) 
print(z3)

tensor([[1, 2],
        [3, 4]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [47]:
# 单元素张量如果您有一个单元素张量，例如通过将张量的所有值聚合为一个值，
# 您可以使用以下方法将其转换为 Python 数值item()
tensor = torch.rand(2,2)
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(agg)
print(agg_item, type(agg_item))

tensor([[0.7300, 0.8589],
        [0.4438, 0.9387]])
tensor(2.9714)
2.9714345932006836 <class 'float'>


In [48]:
# 就地操作
print(tensor, "\n")
# 加减某一固定数值
tensor.add_(5)
print(tensor)

tensor([[0.7300, 0.8589],
        [0.4438, 0.9387]]) 

tensor([[5.7300, 5.8589],
        [5.4438, 5.9387]])


### 使用NumPy桥接

In [49]:
# 张量到numpy数组
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")